# This workflow will run once a day at 07:00 UTC to build and deploy your Jekyll site.
# This allows you to "schedule" posts by dating them in the future.

name: Scheduled Jekyll Deploy

on:
  # Run on pushes to the main branch
  push:
    branches: [ "main" ]
  # Runs once a day at 07:00 UTC. You can adjust the cron schedule as needed.
  schedule:
    - cron: '0 7 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Match the version you use locally if possible
          bundler-cache: true # Speeds up builds by caching gems

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        # Use the JEKYLL_ENV environment variable to set the build environment
        run: bundle exec jekyll build --source . --destination _site
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4